import math
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

gases_choice = {'H2': [33.2, 12.8, 0.01, 20.25], 'O2': [154.6, 49.8, 0.021, 90.15], 'Ar': [150.8, 48.1, -0.004, 87.35],
                'Cl2': [417, 76, 0.073,  239.05], 'NH3': [405.6, 111.3, 0.25, 239.81], 'F2': [144.3, 51.5, 0.048, 85.15],
                'HCl': [324.6, 82, 0.12, 188.1], 'NO': [180, 64, 0.607, 121.15], 'NO2': [431.4, 100, 0.86, 294.15],
                'H2O': [647.3, 217.6, 0.344, -373.15], 'CH4': [190.6, 45.4, 0.008, 111.55], 'CO2': [304.2, 72.8, 0.225, 194.69]}


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(720, 500)
        MainWindow.setStyleSheet("background-color: rgb(243, 225, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gases = QtWidgets.QComboBox(self.centralwidget)
        self.gases.setEnabled(True)
        self.gases.setGeometry(QtCore.QRect(140, 90, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.gases.setFont(font)
        self.gases.setObjectName("Gases")
        self.gases.addItems(gases_choice.keys())
        self.formula = QtWidgets.QComboBox(self.centralwidget)
        self.formula.setGeometry(QtCore.QRect(460, 90, 200, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.formula.setFont(font)
        self.formula.setObjectName("Formula")
        formula_list = ["Соаве-Редлих-Квонг", "Редлих-Квонг"]
        self.formula.addItems(formula_list)
        self.Tc_Edit = QtWidgets.QTextEdit(self.centralwidget)
        self.Tc_Edit.setEnabled(False)
        self.Tc_Edit.setGeometry(QtCore.QRect(260, 150, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Tc_Edit.setFont(font)
        self.Tc_Edit.setObjectName("Tc_Edit")
        self.Pc_Edit = QtWidgets.QTextEdit(self.centralwidget)
        self.Pc_Edit.setEnabled(False)
        self.Pc_Edit.setGeometry(QtCore.QRect(260, 200, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pc_Edit.setFont(font)
        self.Pc_Edit.setObjectName("Pc_Edit")
        self.V_Edit = QtWidgets.QTextEdit(self.centralwidget)
        self.V_Edit.setGeometry(QtCore.QRect(260, 350, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.V_Edit.setFont(font)
        self.V_Edit.setObjectName("V_Edit")
        self.w_Edit = QtWidgets.QTextEdit(self.centralwidget)
        self.w_Edit.setEnabled(False)
        self.w_Edit.setGeometry(QtCore.QRect(260, 250, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.w_Edit.setFont(font)
        self.w_Edit.setObjectName("w_Edit")
        self.T_Edit = QtWidgets.QTextEdit(self.centralwidget)
        self.T_Edit.setGeometry(QtCore.QRect(260, 300, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.T_Edit.setFont(font)
        self.T_Edit.setObjectName("T_Edit")
        self.Tc = QtWidgets.QLabel(self.centralwidget)
        self.Tc.setGeometry(QtCore.QRect(230, 150, 21, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Tc.setFont(font)
        self.Tc.setObjectName("Tc")
        self.T = QtWidgets.QLabel(self.centralwidget)
        self.T.setGeometry(QtCore.QRect(230, 300, 16, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.T.setFont(font)
        self.T.setObjectName("T")
        self.P = QtWidgets.QLabel(self.centralwidget)
        self.P.setGeometry(QtCore.QRect(430, 430, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.P.setFont(font)
        self.P.setObjectName("P")
        self.result = QtWidgets.QTextEdit(self.centralwidget)
        self.result.setEnabled(False)
        self.result.setGeometry(QtCore.QRect(460, 430, 200, 31))
        self.result.setStyleSheet('color: "black"')
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.formula_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.formula_text.setGeometry(QtCore.QRect(460, 140, 200, 192))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.formula_text.setFont(font)
        self.formula_text.setObjectName("Formula_text")
        self.calc_button = QtWidgets.QPushButton(self.centralwidget)
        self.calc_button.setGeometry(QtCore.QRect(210, 430, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.calc_button.setFont(font)
        self.calc_button.setObjectName("calc_button")
        self.Pc = QtWidgets.QLabel(self.centralwidget)
        self.Pc.setGeometry(QtCore.QRect(230, 200, 21, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pc.setFont(font)
        self.Pc.setObjectName("Pc")
        self.V = QtWidgets.QLabel(self.centralwidget)
        self.V.setGeometry(QtCore.QRect(230, 350, 21, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.V.setFont(font)
        self.V.setObjectName("V")
        self.Gas = QtWidgets.QLabel(self.centralwidget)
        self.Gas.setEnabled(True)
        self.Gas.setGeometry(QtCore.QRect(70, 50, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.Gas.setFont(font)
        self.Gas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Gas.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Gas.setMidLineWidth(18)
        self.Gas.setAlignment(QtCore.Qt.AlignCenter)
        self.Gas.setObjectName("Gas")
        self.Krit_temp = QtWidgets.QLabel(self.centralwidget)
        self.Krit_temp.setGeometry(QtCore.QRect(30, 150, 191, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Krit_temp.setFont(font)
        self.Krit_temp.setObjectName("Krit_temp")
        self.Krit_pres = QtWidgets.QLabel(self.centralwidget)
        self.Krit_pres.setGeometry(QtCore.QRect(30, 200, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Krit_pres.setFont(font)
        self.Krit_pres.setObjectName("Krit_pres")
        self.temp = QtWidgets.QLabel(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(30, 300, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.temp.setFont(font)
        self.temp.setObjectName("temp")
        self.value = QtWidgets.QLabel(self.centralwidget)
        self.value.setGeometry(QtCore.QRect(30, 350, 61, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.value.setFont(font)
        self.value.setObjectName("value")
        self.acentric = QtWidgets.QLabel(self.centralwidget)
        self.acentric.setGeometry(QtCore.QRect(30, 250, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.acentric.setFont(font)
        self.acentric.setObjectName("acentric")
        self.omega = QtWidgets.QLabel(self.centralwidget)
        self.omega.setGeometry(QtCore.QRect(230, 250, 21, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.omega.setFont(font)
        self.omega.setObjectName("omega")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 152, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 200, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 305, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(350, 350, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Gas_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gas_2.setEnabled(True)
        self.Gas_2.setGeometry(QtCore.QRect(470, 50, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.Gas_2.setFont(font)
        self.Gas_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Gas_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Gas_2.setMidLineWidth(18)
        self.Gas_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Gas_2.setObjectName("Gas_2")
        self.Gas_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gas_3.setEnabled(True)
        self.Gas_3.setGeometry(QtCore.QRect(159, 10, 381, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.Gas_3.setFont(font)
        self.Gas_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Gas_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Gas_3.setMidLineWidth(18)
        self.Gas_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Gas_3.setObjectName("Gas_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(670, 430, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Газосчиталочка"))
        self.gases.setItemText(0, _translate("MainWindow", "H2"))
        self.gases.setItemText(1, _translate("MainWindow", "O2"))
        self.gases.setItemText(2, _translate("MainWindow", "Ar"))
        self.gases.setItemText(3, _translate("MainWindow", "Cl2"))
        self.formula.setItemText(0, _translate("MainWindow", "Соаве-Редлих-Квонг"))
        self.Tc.setText(_translate("MainWindow", "Tc"))
        self.T.setText(_translate("MainWindow", "T"))
        self.P.setText(_translate("MainWindow", "P"))
        self.calc_button.setText(_translate("MainWindow", "Вычислить"))
        self.Pc.setText(_translate("MainWindow", "Pc"))
        self.V.setText(_translate("MainWindow", "V"))
        self.Gas.setText(_translate("MainWindow", "Газ"))
        self.Krit_temp.setText(_translate("MainWindow", "Критическая температура"))
        self.Krit_pres.setText(_translate("MainWindow", "Критическое давление"))
        self.temp.setText(_translate("MainWindow", "Температура"))
        self.value.setText(_translate("MainWindow", "Объем"))
        self.acentric.setText(_translate("MainWindow", "Ацентрический фактор"))
        self.omega.setText(_translate("MainWindow", "ω"))
        self.label.setText(_translate("MainWindow", "Давление"))
        self.label_2.setText(_translate("MainWindow", "K"))
        self.label_3.setText(_translate("MainWindow", "Па"))
        self.label_4.setText(_translate("MainWindow", "K"))
        self.label_5.setText(_translate("MainWindow", "м³/моль"))
        self.Gas_2.setText(_translate("MainWindow", "Уравнение"))
        self.Gas_3.setText(_translate("MainWindow", "Калькулятор физических свойств газов"))
        self.label_6.setText(_translate("MainWindow", "Па"))
        self.add_functions()

    def add_functions(self):
        self.calc_button.clicked.connect(self.calculate)
        self.gases.currentIndexChanged.connect(self.chng)
        self.chng()

    def calculate(self):
        error = QMessageBox()
        error.setWindowTitle("Ошибка")
        error.setIcon(QMessageBox.Warning)
        error.setStandardButtons(QMessageBox.Ok)
        try:
            if (float(self.T_Edit.toPlainText()) >= 0) and (float(self.T_Edit.toPlainText())<(gases_choice[self.gases.currentText()][3])):
                if self.formula.currentText() == "Соаве-Редлих-Квонг":
                    res = round(self.RKS(float(self.V_Edit.toPlainText()), float(self.T_Edit.toPlainText()),
                                         float(self.Tc_Edit.toPlainText()), float(self.Pc_Edit.toPlainText()),
                                         float(self.w_Edit.toPlainText())), 4)
                    self.result.setText(str(res))
                    self.formula_text.setText("P = (R * T / (V - b)) - (a / (V * (V + b)))")
                elif self.formula.currentText() == "Редлих-Квонг":
                    res = round(self.RK(float(self.V_Edit.toPlainText()), float(self.T_Edit.toPlainText()),
                                        float(self.Tc_Edit.toPlainText()), float(self.Pc_Edit.toPlainText())), 4)
                    self.result.setText(str(res))
                    self.formula_text.setText("P = (R * T / (V - b)) - (a / ((T ** (0.5)) * V * (V + b)))")
            else:
                error.setText("Пожалуйста, введите допустимые значения температуры")
                error.setDetailedText("Температура по Кельвину не может быть отрицательной и должна быть ниже температуры кипения (0≤T<Tкип.)")
                error.exec_()
        except:
            error.setText("Пожалуйста, введите численные значения")
            error.setDetailedText("Необходимо ввести физические переменные, они не могут быть чем-либо, кроме чисел.")
            error.exec_()

    def chng(self):
        for key in gases_choice:
            if self.gases.currentText() == key:
                self.Tc_Edit.setText(str(gases_choice[key][0]))
                self.Pc_Edit.setText(str(gases_choice[key][1]))
                self.w_Edit.setText(str(gases_choice[key][2]))


    def RKS(self, V, T, Tc, Pc, w):
        R = 8.31
        nu_a = 0.42747
        nu_b = 0.08664
        c = 0
        d = 0
        beta = 1
        m = 0.48 + 1.576 * w - 0.176 * (w ** 2)
        alpha = (1 + m * (1 - (math.sqrt(T / Tc)))) ** 2
        a = nu_a * (R ** 2) * (Tc ** 2) * alpha / Pc
        b = nu_b * R * Tc * beta / Pc
        P = (R * T / (V - b)) - (a / (V * (V + b)))
        return P

    def RK(self, V, T, Tc, Pc):
        R = 8.31
        nu_a = 0.42747
        nu_b = 0.08664
        c = 0
        d = 0
        a = nu_a * (R ** 2) * (Tc ** 2.5) / Pc
        b = nu_b * R * Tc / Pc
        P = (R * T / (V - b)) - (a / ((T ** 0.5) * V * (V + b)))
        return P


if __name__ == "__main__":

    try:
        # Блок try/except для подержки Linux/MacOS
        from PyQt5.QtWinExtras import QtWin

        myappid = 'codedog.gasoschet.demo'
        QtWin.setCurrentProcessExplicitAppUserModelID(myappid)
    except ImportError:
        pass
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon('gas.ico'))
    window = QtWidgets.QWidget()
    window.setWindowIcon(QtGui.QIcon('gas.ico'))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
